version: "2"
services:
  grafana:
    build:
      context: ./metrics/Qa/grafana 
      dockerfile: Dockerfile  
      args: 
        version: 1
    image: grafana-qa
    restart: always
    ports:
      - 3000:3000
    networks: 
      - pizza_delicious_network
  prometheus:
    build:
      context: ./metrics/Qa/prometheus
      dockerfile: Dockerfile  
      args: 
        version: 1
    image: prometheus-qa
    restart: always
    ports:
      - 9090:9090
    networks: 
      - pizza_delicious_network
    volumes:
      - ./metrics/Qa/prometheus/data/prometheus:/data
  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile  
  #     args: 
  #       version: 1
  #   image: "app-pizza-delicious-image"
  #   ports:
  #     - "9035:80"
  #   networks: 
  #     - pizza_delicious_network

networks:
  pizza_delicious_network:
    driver: overlay