# config file version
apiVersion: 1

datasources:
  - name: pizza-delicious-prometheus-metrics
    editable: true
    type: prometheus
    access: direct
    url: http://localhost:9090
    isDefault: true
